author: Jazys
description: Docker compose command
homepage: https://github.com/Jazys/espanso-docker-compose
name: docker-compose
title: docker-compose
version: 0.1.0
tags: ["shell", "docker", "alias"]