#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'p:os'
    template = '{{.Icon}} '

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .Shell}} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:pink'
    template = '{{ .Folder}} '

    [blocks.segments.properties]
      folder_icon = '..'
      home_icon = '~'
      style = 'agnoster_short'
      hide_root_location = true
      max_depth = 1

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:lavender'
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:closer'
    template = ''
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#F47AD4'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[palette]
  blue = '#8CAAEE'
  closer = 'p:os'
  lavender = '#BABBF1'
  os = '#ACB0BE'
  pink = '#F4B8E4'
